[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/pipeline"
  status = 200
